### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ERnsTL** [ematvey/gostat#7]
Greetings, this project's license status is unclear and therefore I currently have to avoid it.

Please add a file named ```LICENSE``` or ```LICENSE.md``` containing a stated license.

**Comment by ematvey** [comment]
Good point. Since the original code at Google Code was licensed as BSD 3-Clause, I'm replicating it here.

https://github.com/ematvey/gostat/commit/98c5a598dfa34a3fd5ae6d7cdf846a39e0efd1a4
